// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA07ezU3umAV2atOuSUUeZEGbk7Aylij3k',
    appId: '1:289337442557:web:8532eb0c79b5ece4cd7e94',
    messagingSenderId: '289337442557',
    projectId: 'jugos-casa-blanca',
    authDomain: 'jugos-casa-blanca.firebaseapp.com',
    storageBucket: 'jugos-casa-blanca.appspot.com',
    measurementId: 'G-CWC4BYCGZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWtpGHv7Gh-IlK0dD9IvjJhtsxi52K1Ec',
    appId: '1:289337442557:android:e11b5a988824aa59cd7e94',
    messagingSenderId: '289337442557',
    projectId: 'jugos-casa-blanca',
    storageBucket: 'jugos-casa-blanca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGTpX8G4P03C77BxbTE0jpZr7tAnjccW8',
    appId: '1:289337442557:ios:e7245f1e4c294b6fcd7e94',
    messagingSenderId: '289337442557',
    projectId: 'jugos-casa-blanca',
    storageBucket: 'jugos-casa-blanca.appspot.com',
    iosBundleId: 'com.example.jugosCasablanca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGTpX8G4P03C77BxbTE0jpZr7tAnjccW8',
    appId: '1:289337442557:ios:e7245f1e4c294b6fcd7e94',
    messagingSenderId: '289337442557',
    projectId: 'jugos-casa-blanca',
    storageBucket: 'jugos-casa-blanca.appspot.com',
    iosBundleId: 'com.example.jugosCasablanca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA07ezU3umAV2atOuSUUeZEGbk7Aylij3k',
    appId: '1:289337442557:web:71871135519476a2cd7e94',
    messagingSenderId: '289337442557',
    projectId: 'jugos-casa-blanca',
    authDomain: 'jugos-casa-blanca.firebaseapp.com',
    storageBucket: 'jugos-casa-blanca.appspot.com',
    measurementId: 'G-KTS4HX8RZ0',
  );
}
